### ISSUE TITLE
AttributeError: module 'umap' has no attribute 'UMAP'

### ISSUE THREAD

**Issue by aleksandar-devedzic** [wjbmattingly/LeetTopic#12]
I am getting this error:

AttributeError: module 'umap' has no attribute 'UMAP'

I do not know what is going on.

Can you help me?

**Comment by joelsjlee** [comment]
Hi there,
It's hard for me to recreate your error without knowing exactly what kind of environment and dependencies you already have installed. Have you tried using a fresh conda env if you are doing this in conda?

Otherwise, from some other troubleshooting pages with this error ([here](https://stackoverflow.com/questions/57242208/how-to-resolve-the-error-module-umap-has-no-attribute-umap-i-tried-installi) and [here](https://github.com/lmcinnes/umap/issues/828)) you may need to do some combination of uninstalling `umap` and installing `umap-learn`.
